import { randomUUID } from 'node:crypto';
import {
  mkdir,
  readdir,
  readFile,
  rename,
  unlink,
  writeFile,
} from 'node:fs/promises';
import path from 'node:path';

const PROJECT_ROOT = path.resolve(import.meta.dir, '..');
const MIGRATION_DIRECTORY_PATTERN = /^(\d{14})_(.+)$/;
const STATEMENT_BREAKPOINT = '--> statement-breakpoint';

export const DEFAULT_MIGRATIONS_DIRECTORY = path.join(PROJECT_ROOT, 'drizzle');
export const DEFAULT_MANIFEST_FILE = path.join(
  PROJECT_ROOT,
  'src',
  'databases',
  'generated',
  'migrations.ts',
);

export interface DatabaseMigrationManifestEntry {
  toVersion: number;
  name: string;
  statements: string[];
}

export interface BuildDatabaseMigrationManifestOptions {
  check?: boolean;
  manifestFile?: string;
  migrationsDirectory?: string;
}

export interface BuildDatabaseMigrationManifestResult {
  changed: boolean;
  migrationCount: number;
}

function compareCodePoints(left: string, right: string) {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

function isMissingFileError(error: unknown): error is NodeJS.ErrnoException {
  return (
    error instanceof Error &&
    'code' in error &&
    (error as NodeJS.ErrnoException).code === 'ENOENT'
  );
}

async function readFileIfPresent(file: string) {
  try {
    return await readFile(file, 'utf8');
  } catch (error) {
    if (isMissingFileError(error)) return undefined;
    throw error;
  }
}

function quoteTypeScriptString(value: string) {
  let quoted = "'";

  for (const character of value) {
    const codePoint = character.codePointAt(0) ?? 0;

    switch (character) {
      case "'":
        quoted += "\\'";
        break;
      case '\\':
        quoted += '\\\\';
        break;
      case '\b':
        quoted += '\\b';
        break;
      case '\f':
        quoted += '\\f';
        break;
      case '\n':
        quoted += '\\n';
        break;
      case '\r':
        quoted += '\\r';
        break;
      case '\t':
        quoted += '\\t';
        break;
      case '\v':
        quoted += '\\v';
        break;
      default:
        if (codePoint < 0x20 || codePoint === 0x7f) {
          quoted += `\\x${codePoint.toString(16).padStart(2, '0')}`;
        } else if (codePoint === 0x2028 || codePoint === 0x2029) {
          quoted += `\\u${codePoint.toString(16)}`;
        } else {
          quoted += character;
        }
    }
  }

  return `${quoted}'`;
}

export function renderDatabaseMigrationManifest(
  migrations: DatabaseMigrationManifestEntry[],
) {
  const entries = migrations
    .map((migration) => {
      const statements = migration.statements
        .map((statement) => `      ${quoteTypeScriptString(statement)},`)
        .join('\n');

      return [
        '  {',
        `    toVersion: ${migration.toVersion},`,
        `    name: ${quoteTypeScriptString(migration.name)},`,
        '    statements: [',
        statements,
        '    ],',
        '  },',
      ].join('\n');
    })
    .join('\n');

  return [
    '// Generated by scripts/build-database-migrations.ts.',
    '// Do not edit this file directly; edit the Drizzle migrations instead.',
    '',
    'export interface GeneratedDatabaseMigration {',
    '  readonly toVersion: number;',
    '  readonly name: string;',
    '  readonly statements: readonly [string, ...string[]];',
    '}',
    '',
    'export const GENERATED_DATABASE_MIGRATIONS = [',
    entries,
    '] as const satisfies readonly GeneratedDatabaseMigration[];',
    '',
  ].join('\n');
}

export async function readDatabaseMigrations(
  migrationsDirectory = DEFAULT_MIGRATIONS_DIRECTORY,
) {
  let directoryEntries;

  try {
    directoryEntries = await readdir(migrationsDirectory, {
      withFileTypes: true,
    });
  } catch (error) {
    if (isMissingFileError(error)) {
      throw new Error(
        `Migration directory does not exist: ${migrationsDirectory}. Run bun run db:generate first.`,
      );
    }
    throw error;
  }

  const migrationDirectories = directoryEntries
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const match = MIGRATION_DIRECTORY_PATTERN.exec(entry.name);
      if (!match) {
        throw new Error(
          `Unexpected directory in Drizzle migrations: ${entry.name}. Expected YYYYMMDDHHMMSS_name.`,
        );
      }

      return {
        name: entry.name,
        timestamp: match[1] ?? '',
      };
    })
    .sort((left, right) => compareCodePoints(left.name, right.name));

  if (migrationDirectories.length === 0) {
    throw new Error(
      `No Drizzle migrations found in ${migrationsDirectory}. Run bun run db:generate first.`,
    );
  }

  for (let index = 1; index < migrationDirectories.length; index += 1) {
    const previous = migrationDirectories[index - 1];
    const current = migrationDirectories[index];

    if (!previous || !current) continue;

    if (previous.timestamp === current.timestamp) {
      throw new Error(
        `Migration directories ${previous.name} and ${current.name} have the same timestamp; their upgrade order would be ambiguous.`,
      );
    }
  }

  return await Promise.all(
    migrationDirectories.map(async (migration, index) => {
      const migrationFile = path.join(
        migrationsDirectory,
        migration.name,
        'migration.sql',
      );
      const sql = await readFileIfPresent(migrationFile);

      if (sql === undefined) {
        throw new Error(`Missing Drizzle migration SQL: ${migrationFile}`);
      }

      const statements = sql
        .split(STATEMENT_BREAKPOINT)
        .map((statement) => statement.trim())
        .filter((statement) => statement.length > 0);

      if (statements.length === 0) {
        throw new Error(
          `Drizzle migration contains no SQL statements: ${migrationFile}`,
        );
      }

      return {
        toVersion: index + 1,
        name: migration.name,
        statements,
      } satisfies DatabaseMigrationManifestEntry;
    }),
  );
}

export async function buildDatabaseMigrationManifest(
  options: BuildDatabaseMigrationManifestOptions = {},
): Promise<BuildDatabaseMigrationManifestResult> {
  const {
    check = false,
    manifestFile = DEFAULT_MANIFEST_FILE,
    migrationsDirectory = DEFAULT_MIGRATIONS_DIRECTORY,
  } = options;
  const migrations = await readDatabaseMigrations(migrationsDirectory);
  const expected = renderDatabaseMigrationManifest(migrations);
  const current = await readFileIfPresent(manifestFile);

  if (current === expected) {
    return { changed: false, migrationCount: migrations.length };
  }

  if (check) {
    throw new Error(
      `Generated migration manifest is stale or missing: ${manifestFile}. Run bun run db:migrations:build.`,
    );
  }

  await mkdir(path.dirname(manifestFile), { recursive: true });
  const temporaryFile = path.join(
    path.dirname(manifestFile),
    `.${path.basename(manifestFile)}.${process.pid}.${randomUUID()}.tmp`,
  );

  try {
    await writeFile(temporaryFile, expected, {
      encoding: 'utf8',
      flag: 'wx',
    });
    await rename(temporaryFile, manifestFile);
  } finally {
    await unlink(temporaryFile).catch((error: unknown) => {
      if (!isMissingFileError(error)) throw error;
    });
  }

  return { changed: true, migrationCount: migrations.length };
}

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}

if (import.meta.main) {
  try {
    const check = process.argv.slice(2).includes('--check');
    const result = await buildDatabaseMigrationManifest({ check });
    const action = check
      ? 'verified'
      : result.changed
        ? 'generated'
        : 'already current';

    console.info(
      `[database] Migration manifest ${action} (${result.migrationCount} migrations).`,
    );
  } catch (error) {
    console.error(`[database] ${errorMessage(error)}`);
    process.exitCode = 1;
  }
}
