/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TabbarRouteImport } from './../routes/_tabbar'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as TabbarPreferencesRouteImport } from './../routes/_tabbar/preferences'
import { Route as TabbarDashboardRouteImport } from './../routes/_tabbar/dashboard'
import { Route as TabbarCalendarRouteImport } from './../routes/_tabbar/calendar'

const TabbarRoute = TabbarRouteImport.update({
  id: '/_tabbar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabbarPreferencesRoute = TabbarPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => TabbarRoute,
} as any)
const TabbarDashboardRoute = TabbarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TabbarRoute,
} as any)
const TabbarCalendarRoute = TabbarCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TabbarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof TabbarCalendarRoute
  '/dashboard': typeof TabbarDashboardRoute
  '/preferences': typeof TabbarPreferencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof TabbarCalendarRoute
  '/dashboard': typeof TabbarDashboardRoute
  '/preferences': typeof TabbarPreferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabbar': typeof TabbarRouteWithChildren
  '/_tabbar/calendar': typeof TabbarCalendarRoute
  '/_tabbar/dashboard': typeof TabbarDashboardRoute
  '/_tabbar/preferences': typeof TabbarPreferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/dashboard' | '/preferences'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/dashboard' | '/preferences'
  id:
    | '__root__'
    | '/'
    | '/_tabbar'
    | '/_tabbar/calendar'
    | '/_tabbar/dashboard'
    | '/_tabbar/preferences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabbarRoute: typeof TabbarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabbar': {
      id: '/_tabbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabbar/preferences': {
      id: '/_tabbar/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof TabbarPreferencesRouteImport
      parentRoute: typeof TabbarRoute
    }
    '/_tabbar/dashboard': {
      id: '/_tabbar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof TabbarDashboardRouteImport
      parentRoute: typeof TabbarRoute
    }
    '/_tabbar/calendar': {
      id: '/_tabbar/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof TabbarCalendarRouteImport
      parentRoute: typeof TabbarRoute
    }
  }
}

interface TabbarRouteChildren {
  TabbarCalendarRoute: typeof TabbarCalendarRoute
  TabbarDashboardRoute: typeof TabbarDashboardRoute
  TabbarPreferencesRoute: typeof TabbarPreferencesRoute
}

const TabbarRouteChildren: TabbarRouteChildren = {
  TabbarCalendarRoute: TabbarCalendarRoute,
  TabbarDashboardRoute: TabbarDashboardRoute,
  TabbarPreferencesRoute: TabbarPreferencesRoute,
}

const TabbarRouteWithChildren =
  TabbarRoute._addFileChildren(TabbarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabbarRoute: TabbarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
