import { defineConfig } from '@momots/cli';

export default defineConfig({
  build: {
    splitting: true,
    target: 'browser',
  },
  tarball: {
    imports: [
      '.',
      './buffer',
      './canvas',
      './css/to-css-rgb-variable',
      './css/to-css-variable',
      './css/to-rgb',
      './css/types',
      './fingerprint',
      './fetch',
      './fetch/index',
      './fetch/to-curl',
      './fetch/type',
      './guard/index',
      './guard/is-android',
      './guard/is-android-web',
      './guard/is-array-buffer',
      './guard/is-array-buffer-like',
      './guard/is-array-buffer-view',
      './guard/is-blob',
      './guard/is-buffer-source',
      './guard/is-css-style-rule',
      './guard/is-element',
      './guard/is-form-data',
      './guard/is-hex-string',
      './guard/is-html-element',
      './guard/is-input-element',
      './guard/is-ios',
      './guard/is-ios-web',
      './guard/is-localhost',
      './guard/is-miniprogram',
      './guard/is-mobile',
      './guard/is-non-raw-body-init',
      './guard/is-overflow',
      './guard/is-readable-stream',
      './guard/is-scrollable',
      './guard/is-ssr',
      './guard/is-text-area-element',
      './guard/is-touch-device',
      './guard/is-uint8-array',
      './guard/is-url-search-params',
      './guard/is-wechat',
      './guard/is-wechat-web',
      './nearest',
      './persistent',
      './storage',
    ],
    identities: [
      { export: 'bytesToHex', from: ['.', './buffer'] },
      { export: 'measureText', from: ['.', './canvas'] },
      { export: 'toRGB', from: ['.', './css/to-rgb'] },
      { export: 'projection', from: ['.', './fingerprint'] },
      {
        export: 'toCurl',
        from: ['.', './fetch', './fetch/index', './fetch/to-curl'],
      },
      {
        export: 'isMobile',
        from: ['.', './guard/index', './guard/is-mobile'],
      },
      { export: 'nearestScrollable', from: ['.', './nearest'] },
      { export: 'PersistentBuffer', from: ['.', './persistent'] },
      { export: 'MemoryStorage', from: ['.', './storage'] },
      { export: 'memory', from: ['.', './storage'] },
      { export: 'Storagefy', from: ['.', './storage'] },
      { export: 'StoragefyAsync', from: ['.', './storage'] },
    ],
    check: async ({ consumerDirectory, run }) => {
      await run(
        'node',
        ['--input-type=module', '--eval', "await import('@momots/host')"],
        { cwd: consumerDirectory },
      );
    },
  },
});
